package com.example.quizapp;

import com.example.quizapp.model.*;
import com.example.quizapp.repository.*;
import jakarta.transaction.Transactional;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.security.crypto.password.PasswordEncoder;

import java.util.ArrayList;
import java.util.List;

@SpringBootApplication
public class QuizAppApplication {

    public static void main(String[] args) {
        SpringApplication.run(QuizAppApplication.class, args);
    }

    /**
     * Creates test users with simplified usernames.
     * All users have the password: "password123"
     */
    @Bean
    @Transactional
    CommandLineRunner initDatabase(
            UserRepository userRepository,
            ClassroomRepository classroomRepository,
            QuizRepository quizRepository,
            QuestionRepository questionRepository,
            OptionRepository optionRepository,
            PasswordEncoder passwordEncoder) {

        return args -> {
            // 1. Create Users
            User teacher = createOrGetUser(userRepository, "teacher", "password123", "Bun Menghong", User.Role.ROLE_TEACHER, passwordEncoder);
            User student = createOrGetUser(userRepository, "student", "password123", "Lim Menghour", User.Role.ROLE_STUDENT, passwordEncoder);
            User admin = createOrGetUser(userRepository, "admin", "password123", "Admin User", User.Role.ROLE_ADMIN, passwordEncoder);

            // 2. Create Classroom (Only if teacher has no classes yet)
            if (classroomRepository.findByTeacherId(teacher.getId()).isEmpty()) {
                System.out.println("Seeding database with IT Class and Quiz...");

                Classroom classroom = new Classroom();
                classroom.setName("CS101: Intro to IT");
                classroom.setTeacher(teacher);
                // Code is auto-generated by @PrePersist in Classroom model
                classroomRepository.save(classroom);

                // Auto-enroll the test student
                classroom.getStudents().add(student);
                classroomRepository.save(classroom);

                // 3. Create Quiz
                Quiz quiz = new Quiz();
                quiz.setTitle("IT Fundamentals");
                quiz.setSubject("Information Technology");
                quiz.setTeacher(teacher);
                quiz.setCreator(teacher);
                quiz.setClassroom(classroom);
                quizRepository.save(quiz);

                // 4. Create Questions
                createQuestion(questionRepository, optionRepository, quiz,
                        "Which protocol is used for secure communication over a computer network?",
                        new String[]{"HTTP", "FTP", "HTTPS", "SMTP"}, 2); // HTTPS

                createQuestion(questionRepository, optionRepository, quiz,
                        "What does CPU stand for?",
                        new String[]{"Central Processing Unit", "Computer Personal Unit", "Central Process Utility", "Central Processor Unit"}, 0); // Central Processing Unit

                createQuestion(questionRepository, optionRepository, quiz,
                        "Which component is considered the 'brain' of the computer?",
                        new String[]{"Hard Drive", "RAM", "CPU", "GPU"}, 2); // CPU

                createQuestion(questionRepository, optionRepository, quiz,
                        "What is the main function of the Operating System?",
                        new String[]{"To compile code", "To manage hardware and software resources", "To browse the internet", "To protect against viruses"}, 1); // Manage resources

                createQuestion(questionRepository, optionRepository, quiz,
                        "Which of these is a volatile memory type?",
                        new String[]{"ROM", "HDD", "Flash Memory", "RAM"}, 3); // RAM

                System.out.println("Database seeded successfully!");
            }
        };
    }

    private User createOrGetUser(UserRepository repo, String username, String password, String fullname, User.Role role, PasswordEncoder encoder) {
        return repo.findByUsername(username).orElseGet(() -> {
            User user = new User();
            user.setUsername(username);
            user.setPassword(encoder.encode(password));
            user.setFullName(fullname);
            user.setRole(role);
            return repo.save(user);
        });
    }

    private void createQuestion(QuestionRepository qRepo, OptionRepository oRepo, Quiz quiz, String text, String[] optionsText, int correctIndex) {
        Question q = new Question();
        q.setText(text);
        q.setQuiz(quiz);
        qRepo.save(q);

        List<Option> options = new ArrayList<>();
        for (int i = 0; i < optionsText.length; i++) {
            Option o = new Option();
            o.setText(optionsText[i]);
            o.setCorrect(i == correctIndex);
            o.setQuestion(q);
            options.add(o);
        }
        oRepo.saveAll(options);
    }
}